driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 2048
    nictype1: "Am79C973"
  synced_folders:
    - ['.', '/home/vagrant/omnibus-backup']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/omnibus-backup
