driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/omnibus-backup']

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04
    run_list: apt::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/omnibus-backup
        install_dir: /opt/omnibus-backup
